language: node_js
node_js:
- '0.10'
env:
  global:
  - LOG_LEVEL: error
sudo: false
branches:
  only:
  - master
before_deploy:
- git config --global user.email "nordstrom.ross+gearsmarts@gmail.com"
- git config --global user.name "GearSmarts"
- git add -f doc coverage plato
- git commit -m "Build updating coverage, code complexity, and docs for Deployment"
deploy:
  provider: heroku
  app: gearsmarts
  skip_cleanup: true
  api_key:
    secure: pXeXqcCTu04qpBbDSNWHsYMFUwPzskugFW2ywifG7MWj7hkrMkQhC+QuVT77DphM8FyoUTdvN4OGaVy7m9xbe8HBEyjqNWh8LlqQBUnJjnxNyPwFaxTucuAJHzcdwEXOyK8Bilca8R6HJMMahe6UlgpzJr7Gy1XgD6QnMvP8gew=
